import { Course, Quiz, User, Announcement } from './types';

export const MOCK_USER: User = {
  id: 'u1',
  name: 'John Doe',
  email: 'john.doe@digitalmojo.com',
  avatar: 'https://picsum.photos/seed/user1/200/200',
  joinDate: 'Oct 2023'
};



export const MOCK_COURSES: Course[] = [
  // Mandated / Onboarding
  {
    id: 'c_orient',
    title: 'Welcome to Digital Mojo',
    description: 'Essential company history, culture, values, and handbook review for all new joiners.',
    progress: 0,
    image: 'https://picsum.photos/seed/office/600/400',
    category: 'mandated',
    dueDate: 'In 2 days',
    modules: [
      { id: 'm1', title: 'CEO Welcome Message', description: 'A personal welcome from our leadership team.', duration: '10 min', isCompleted: true, type: 'video', videoUrl: 'https://www.youtube.com/embed/sL6z4-Rak2g' },
      { id: 'm2', title: 'Our Core Values', description: 'Understanding the pillars of our company culture.', duration: '15 min', isCompleted: true, type: 'reading' },
      { id: 'm3', title: 'Employee Handbook Quiz', description: 'Assessment of key policies and procedures.', duration: '20 min', isCompleted: true, type: 'quiz' },
    ],
  },

  // Role Specific
  {
    id: 'c1',
    title: 'Account Manager',
    description: 'Comprehensive training on client retention, growth strategies, and effective communication for Digital Mojo Account Managers.',
    progress: 0,
    image: 'https://picsum.photos/seed/accountmgmt/600/400',
    category: 'role-specific',
    modules: [
      { id: 'm1', title: 'The AM Mindset & Responsibilities', description: 'Understanding your pivotal role in client success.', duration: '15 min', isCompleted: true, type: 'video', videoUrl: 'https://youtu.be/UDVtMYqUAyw?si=-xi89n_6vdPqdfy5' },
      { id: 'm2', title: 'Client Onboarding SOPs', description: 'Step-by-step guide to bringing new clients on board smoothly.', duration: '25 min', isCompleted: false, type: 'reading' },
      { id: 'm3', title: 'Effective Communication Matrix', description: 'Structuring emails and calls for maximum impact.', duration: '30 min', isCompleted: false, type: 'video', videoUrl: 'https://www.youtube.com/embed/sL6z4-Rak2g' },
      { id: 'm4', title: 'Running Quarterly Business Reviews (QBR)', description: 'How to prepare and present value-driven QBRs.', duration: '45 min', isCompleted: false, type: 'video', videoUrl: 'https://www.youtube.com/embed/sL6z4-Rak2g' },
      { id: 'm5', title: 'Negotiation & Upselling Techniques', description: 'Strategies for expanding account value ethically.', duration: '40 min', isCompleted: false, type: 'video', videoUrl: 'https://www.youtube.com/embed/sL6z4-Rak2g' },
      { id: 'm6', title: 'Crisis Management & Churn Prevention', description: 'Handling difficult conversations and saving at-risk accounts.', duration: '35 min', isCompleted: false, type: 'quiz' },
    ],
  },
  {
    id: 'c_perf_spec',
    title: 'Performance Marketing Specialist',
    description: 'Complete certification for Performance Specialists covering Campaign Setup, Ad Launch, Optimization, Budgeting, and Reporting across Google and Meta.',
    progress: 0,
    image: 'https://picsum.photos/seed/ppc/600/400',
    category: 'role-specific',
    modules: [
      {
        id: 'pm_m1',
        title: 'Campaign Setup & Planning',
        description: 'Create campaign plans based on approved strategy from Performance Lead. Understand goals, funnel type, budget, and perform keyword/audience research.',
        duration: '25 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m2',
        title: 'Ad Launch & Quality Check',
        description: 'Set up campaigns on Google, Meta, and LinkedIn Ads Manager. Verify settings, tracking, and perform full test leads before launch.',
        duration: '24 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m3',
        title: 'Campaign Optimization',
        description: 'Monitor live campaigns daily for performance metrics (CTR, CPC, CPL, ROAS). Identify high/low performers and adjust bids/creatives.',
        duration: '25 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m4',
        title: 'Budget Monitoring',
        description: 'Track daily and weekly spend against allocated budget. Adjust pacing to prevent over- or under-spending and reallocate dynamically.',
        duration: '24 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m5',
        title: 'Reporting & Analysis',
        description: 'Prepare weekly reports showing campaign performance and key insights. Highlight learning points, creative winners, and improvement areas.',
        duration: '24 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m6',
        title: 'Cross-Team Coordination',
        description: 'Collaborate with Account team for new client goals. Share ad performance data with Creative team and work with SEO/Automation teams.',
        duration: '20 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m7',
        title: 'AI & Automation Integration',
        description: 'Use AI tools (ChatGPT, AdCreative.ai) for ad copy and creative suggestions. Leverage Meta Advantage+ and automate reporting dashboards.',
        duration: '20 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m8',
        title: 'Client Updates & Escalations',
        description: 'Share ad highlights and reports with Account team weekly. Flag campaign issues proactively and ensure transparent communication.',
        duration: '20 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m9',
        title: 'Process & SOP Adherence',
        description: 'Follow performance SOP for campaign setup, optimization, and reporting. Update trackers daily and submit campaign audit forms.',
        duration: '20 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m10',
        title: 'Knowledge Transfer & Handover',
        description: 'Follow KT template. Document pending tasks, red alerts, and update trackers. Ensure smooth continuity during leaves.',
        duration: '16 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m11',
        title: 'Conversion Tracking & LP Mgmt',
        description: 'Verify pixels, tracking events, and UTM parameters. Run test leads and monitor landing page speed and UX.',
        duration: '25 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m12',
        title: 'Audience, Keyword & Creative Strategy',
        description: 'Develop keyword and audience clusters. Monitor fatigue, test creatives, and study competitors. Build ongoing strategy.',
        duration: '25 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m13',
        title: 'Onboarding & New Client Setup',
        description: 'Collect and verify all accesses. Create folder structures, audit previous performance, and prepare first-month blueprints.',
        duration: '25 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m14',
        title: 'Tools, Diagnostics & Troubleshooting',
        description: 'Use platform diagnostics and debug tools (GTM, GA4, Pixel Helper) to identify root causes of performance issues.',
        duration: '24 min',
        isCompleted: false,
        type: 'video'
      },
      {
        id: 'pm_m15',
        title: 'Red Alert Detection & Recovery',
        description: 'Identify major drops fast. Systematic diagnosis of delivery, creative, budget, and tracking. Create and execute recovery plans.',
        duration: '25 min',
        isCompleted: false,
        type: 'video'
      },
    ],
  },
  {
    id: 'c3',
    title: 'Web Developer',
    description: 'Full-stack fundamentals covering Wordpress, PHP, MySQL, and modern backend integration.',
    progress: 0,
    image: 'https://picsum.photos/seed/webdev/600/400',
    category: 'role-specific',
    modules: [
      { id: 'm1', title: 'Semantic HTML & CSS Grid', description: 'Building accessible and responsive layouts.', duration: '35 min', isCompleted: false, type: 'video' },
      { id: 'm2', title: 'JavaScript ES6+', description: 'Mastering modern JavaScript features.', duration: '40 min', isCompleted: false, type: 'video' },
      { id: 'm3', title: 'React Hooks Intro', description: 'Understanding state and side effects in React.', duration: '25 min', isCompleted: false, type: 'reading' },
    ],
  },
  {
    id: 'c4',
    title: 'Advanced SEO Mastery',
    description: 'Learn technical SEO, on-page optimization, and backlink strategies to rank #1.',
    progress: 0,
    image: 'https://picsum.photos/seed/seocourse/600/400',
    category: 'role-specific',
    modules: [
      { id: 'm1', title: 'Search Engine Algorithms', description: 'How Google ranks content in 2024.', duration: '15 min', isCompleted: false, type: 'video' },
      { id: 'm2', title: 'Keyword Research Tools', description: 'Finding high-opportunity keywords.', duration: '30 min', isCompleted: false, type: 'video' },
      { id: 'm3', title: 'Technical SEO Audits', description: 'Identifying and fixing crawl errors.', duration: '25 min', isCompleted: false, type: 'quiz' },
    ],
  },
];

// Updated Quizzes
export const MOCK_QUIZZES: Record<string, Quiz> = {
  'q_pm_m1': {
    id: 'q_pm_m1',
    title: 'Campaign Setup & Planning Assessment',
    moduleId: 'pm_m1',
    totalQuestions: 10,
    timeLimit: '18:00',
    questions: [
      { id: 'q1', text: 'What is the first step in campaign setup?', options: ['Launching ads', 'Understanding goals', 'Writing copy', 'Uploading creatives'], correctOptionIndex: 1 },
      { id: 'q2', text: 'Naming conventions help with:', options: ['Confusion', 'Clear structure', 'Hiding details', 'Randomness'], correctOptionIndex: 1 },
      { id: 'q3', text: 'Keyword research is required for:', options: ['Meta only', 'Google Search', 'Instagram Stories', 'Email'], correctOptionIndex: 1 },
      { id: 'q4', text: 'UTMs track:', options: ['Fonts', 'Source/performance', 'Competitors', 'Emails'], correctOptionIndex: 1 },
      { id: 'q5', text: 'Landing page must be:', options: ['Slow', 'Confusing', 'Fast & clear', 'Hidden'], correctOptionIndex: 2 },
      { id: 'q6', text: 'Pixel ensures:', options: ['Creative quality', 'Conversion tracking', 'Budget increase', 'Trend accuracy'], correctOptionIndex: 1 },
      { id: 'q7', text: 'Who provides assets?', options: ['Performance', 'Creative', 'Sales', 'Security'], correctOptionIndex: 1 },
      { id: 'q8', text: 'Test leads checked in:', options: ['CRM + sheet', 'Canva', 'WhatsApp', 'Email'], correctOptionIndex: 0 },
      { id: 'q9', text: 'Audience research helps:', options: ['Music selection', 'Targeting accuracy', 'Color palette', 'Budget approval'], correctOptionIndex: 1 },
      { id: 'q10', text: 'Onboarding SOP ensures:', options: ['Waste', 'Readiness', 'High cost', 'Delay'], correctOptionIndex: 1 },
    ],
  },
  'q_pm_m2': {
    id: 'q_pm_m2',
    title: 'Ad Launch & Quality Check Assessment',
    moduleId: 'pm_m2',
    totalQuestions: 10,
    timeLimit: '18:00',
    questions: [
      { id: 'q1', text: 'What is the purpose of QC?', options: ['Delay launch', 'Avoid expensive mistakes', 'Confuse team', 'Slow down work'], correctOptionIndex: 1 },
      { id: 'q2', text: 'Tracking must be checked before launch:', options: ['Never', 'Only sometimes', 'Always', 'After launch'], correctOptionIndex: 2 },
      { id: 'q3', text: 'Test leads must reflect in:', options: ['CRM + lead sheet', 'WhatsApp', 'Canva', 'Email only'], correctOptionIndex: 0 },
      { id: 'q4', text: 'Landing page must be checked for:', options: ['Speed & CTA', 'Font size only', 'Colors only', 'Nothing'], correctOptionIndex: 0 },
      { id: 'q5', text: 'Ads must not be launched without:', options: ['Client approval', 'QC approval', 'Random approval', 'Designer approval'], correctOptionIndex: 1 },
      { id: 'q6', text: 'Incorrect UTMs cause:', options: ['Better tracking', 'Broken analytics', 'Higher leads', 'Faster delivery'], correctOptionIndex: 1 },
      { id: 'q7', text: 'Naming conventions must be:', options: ['Optional', 'Followed strictly', 'Random', 'Stylish'], correctOptionIndex: 1 },
      { id: 'q8', text: 'Final preview check ensures:', options: ['Correct copy and visuals', 'Fast spending', 'More impressions', 'CTR drop'], correctOptionIndex: 0 },
      { id: 'q9', text: 'Missing pixel events lead to:', options: ['Cheaper CPL', 'No conversion tracking', 'Fast approvals', 'Better ROAS'], correctOptionIndex: 1 },
      { id: 'q10', text: 'LP broken on mobile → next step?', options: ['Launch anyway', 'Fix immediately', 'Ignore', 'Increase budget'], correctOptionIndex: 1 },
    ],
  },
  'q_pm_m3': {
    id: 'q_pm_m3',
    title: 'Campaign Optimization Assessment',
    moduleId: 'pm_m3',
    totalQuestions: 10,
    timeLimit: '18:00',
    questions: [
      { id: 'q1', text: 'What is the goal of daily optimization?', options: ['Random testing', 'Improve performance and maintain control', 'Spend budgets faster', 'Avoid changes'], correctOptionIndex: 1 },
      { id: 'q2', text: 'High CPL ads should be:', options: ['Ignored', 'Switched off or fixed', 'Boosted', 'Left running'], correctOptionIndex: 1 },
      { id: 'q3', text: 'Negative keywords are used to:', options: ['Increase cost', 'Block irrelevant searches', 'Reduce impressions', 'Track UTMs'], correctOptionIndex: 1 },
      { id: 'q4', text: 'A weak creative should be:', options: ['Removed or replaced', 'Ignored', 'Used more', 'Hidden'], correctOptionIndex: 0 },
      { id: 'q5', text: 'Lead quality checks must be done:', options: ['Never', 'Only monthly', 'Regularly using CRM', 'Only after complaints'], correctOptionIndex: 2 },
      { id: 'q6', text: 'Bid adjustments help with:', options: ['Impressions and cost control', 'Creative quality', 'Landing page design', 'CRM setup'], correctOptionIndex: 0 },
      { id: 'q7', text: 'Daily updates must be:', options: ['Avoided', 'Logged in tracker', 'Sent randomly', 'Skipped'], correctOptionIndex: 1 },
      { id: 'q8', text: 'Optimization decisions should be based on:', options: ['Guessing', 'Data and trends', 'Opinions', 'Visuals only'], correctOptionIndex: 1 },
      { id: 'q9', text: 'Daily coordination with AM is needed for:', options: ['No reason', 'Smooth execution', 'Approvals only', 'Design fixes'], correctOptionIndex: 1 },
      { id: 'q10', text: 'If CPL spikes suddenly:', options: ['Ignore', 'Act immediately', 'Wait a week', 'Ask designer'], correctOptionIndex: 1 },
    ],
  },
  'q_pm_m4': {
    id: 'q_pm_m4',
    title: 'Budget Monitoring Assessment',
    moduleId: 'pm_m4',
    totalQuestions: 10,
    timeLimit: '18:00',
    questions: [
      { id: 'q1', text: 'What is the purpose of pacing?', options: ['Spend randomly', 'Ensure budgets last the entire month', 'Increase CPL', 'Reduce impressions'], correctOptionIndex: 1 },
      { id: 'q2', text: 'Overspending requires:', options: ['Higher budgets', 'Reducing bids or pausing poor segments', 'Ignoring', 'Posting more stories'], correctOptionIndex: 1 },
      { id: 'q3', text: 'Underspending requires:', options: ['Doing nothing', 'Expanding audiences or increasing bids', 'Deleting campaigns', 'Lowering LP speed'], correctOptionIndex: 1 },
      { id: 'q4', text: 'Reallocating budget helps:', options: ['Waste money', 'Boost strong performers', 'Increase load time', 'Reduce leads'], correctOptionIndex: 1 },
      { id: 'q5', text: 'Red-alert means:', options: ['Low CPC', 'CPL spike or delivery issues', 'Many comments', 'Too many creatives'], correctOptionIndex: 1 },
      { id: 'q6', text: 'Daily budget logs must be:', options: ['Optional', 'Recorded in tracker', 'Sent to designer', 'Hidden'], correctOptionIndex: 1 },
      { id: 'q7', text: 'Weekly pacing checks prevent:', options: ['Overthinking', 'Last-minute spending problems', 'More work', 'Client meetings'], correctOptionIndex: 1 },
      { id: 'q8', text: 'If pacing is too slow:', options: ['Reduce bids', 'Increase bids or audiences', 'Pause all ads', 'Ask designer'], correctOptionIndex: 1 },
      { id: 'q9', text: 'If one ad set is over-consuming:', options: ['Pause or limit it', 'Boost it', 'Let it run', 'Duplicate everything'], correctOptionIndex: 0 },
      { id: 'q10', text: 'Budget monitoring ensures:', options: ['Wasteful spend', 'Efficient use of ad money', 'Designer happiness', 'More meetings'], correctOptionIndex: 1 },
    ],
  },
  'q_pm_m5': {
    id: 'q_pm_m5',
    title: 'Reporting & Analysis Assessment',
    moduleId: 'pm_m5',
    totalQuestions: 10,
    timeLimit: '18:00',
    questions: [
      { id: 'q1', text: 'Reporting converts:', options: ['Numbers into clarity', 'Clarity into confusion', 'Ads into designs', 'Creatives into scripts'], correctOptionIndex: 0 },
      { id: 'q2', text: 'Daily dashboards require:', options: ['Guessing', 'Accurate CPL, spend, and tracking', 'Only CTR', 'Only impressions'], correctOptionIndex: 1 },
      { id: 'q3', text: 'Weekly reports should highlight:', options: ['Only wins', 'Trends and insights', 'Only CPC', 'Only reach'], correctOptionIndex: 1 },
      { id: 'q4', text: 'GA4 helps you understand:', options: ['Fonts', 'Landing page behaviour', 'Ad colors', 'Creative size'], correctOptionIndex: 1 },
      { id: 'q5', text: 'Clarity shows:', options: ['Scroll and click behaviour', 'Ad approval times', 'Budget errors', 'Video lengths'], correctOptionIndex: 0 },
      { id: 'q6', text: 'Monthly reports include:', options: ['Screenshots only', 'Winners, losers, insights, next steps', 'Only CPL', 'Only creative names'], correctOptionIndex: 1 },
      { id: 'q7', text: 'Creative fatigue shows when:', options: ['CTR increases', 'CTR drops and CPL rises', 'CPC becomes zero', 'LP traffic becomes high'], correctOptionIndex: 1 },
      { id: 'q8', text: 'Keyword insights help you:', options: ['Improve creative design', 'Refine search strategy', 'Change LP color', 'Write emails'], correctOptionIndex: 1 },
      { id: 'q9', text: 'Good reporting leads to:', options: ['Wrong targeting', 'Better strategy and decisions', 'Confusion', 'Higher lead cost'], correctOptionIndex: 1 },
      { id: 'q10', text: 'Missing tracking in report means:', options: ['Minor issue', 'Entire data is unreliable', 'Good news', 'Does not matter'], correctOptionIndex: 1 },
    ],
  },
  'q_pm_m6': {
    id: 'q_pm_m6',
    title: 'Cross-Team Coordination Assessment',
    moduleId: 'pm_m6',
    totalQuestions: 10,
    timeLimit: '15:00',
    questions: [
      { id: 'q1', text: 'Cross-team coordination helps:', options: ['Reduce clarity', 'Improve execution speed', 'Block communication', 'Increase CPL'], correctOptionIndex: 1 },
      { id: 'q2', text: 'AMs must be updated because:', options: ['They talk to clients', 'They manage reporting', 'They align expectations', 'All of the above'], correctOptionIndex: 3 },
      { id: 'q3', text: 'Creative fatigue requires:', options: ['Ignoring', 'Immediate new creatives', 'Pausing all ads', 'Reducing CPC'], correctOptionIndex: 1 },
      { id: 'q4', text: 'Web/Landing team helps with:', options: ['Video editing', 'CRO and form fixes', 'Lead sheet updates', 'UTM writing'], correctOptionIndex: 1 },
      { id: 'q5', text: 'Automation team fixes:', options: ['Designs', 'CRM + Pabbly issues', 'Copywriting', 'SEO'], correctOptionIndex: 1 },
      { id: 'q6', text: 'Weekly coordination meeting is for:', options: ['Food menu', 'Account-level insights', 'Ad approvals', 'Music choices'], correctOptionIndex: 1 },
      { id: 'q7', text: 'Not coordinating with Creative can cause:', options: ['Lower CTR', 'Higher CPL', 'Delayed launches', 'All of the above'], correctOptionIndex: 3 },
      { id: 'q8', text: 'AM update frequency must be:', options: ['Weekly', 'Daily', 'Monthly', 'Random'], correctOptionIndex: 1 },
      { id: 'q9', text: 'Duplicate leads usually mean:', options: ['Pixel issue', 'CRM/Pabbly error', 'Creative error', 'SEO problem'], correctOptionIndex: 1 },
      { id: 'q10', text: 'If LP tracking breaks:', options: ['Ignore', 'Fix with Web + Automation teams', 'Reduce budget only', 'Pause GMB'], correctOptionIndex: 1 },
    ],
  },
  'q_pm_m7': {
    id: 'q_pm_m7',
    title: 'AI & Automation Integration Assessment',
    moduleId: 'pm_m7',
    totalQuestions: 10,
    timeLimit: '15:00',
    questions: [
      { id: 'q1', text: 'AI helps you:', options: ['Slow work', 'Speed up and improve accuracy', 'Replace team', 'Reduce tracking'], correctOptionIndex: 1 },
      { id: 'q2', text: 'AI should be used for:', options: ['Copy drafts', 'Audience research', 'Competitor analysis', 'All of the above'], correctOptionIndex: 3 },
      { id: 'q3', text: 'Meta Advantage+ and Google automation improve:', options: ['Delivery and performance', 'Video quality', 'Website design', 'Colour palette'], correctOptionIndex: 0 },
      { id: 'q4', text: 'AI dashboards help with:', options: ['Screenshots', 'Summaries & anomaly detection', 'Fonts', 'Story posting'], correctOptionIndex: 1 },
      { id: 'q5', text: 'Automating tracking prevents:', options: ['Mistakes', 'Fast loading', 'Extra meetings', 'Low impressions'], correctOptionIndex: 0 },
      { id: 'q6', text: 'AI experiments must be:', options: ['Random', 'Logged for learning', 'Hidden', 'Avoided'], correctOptionIndex: 1 },
      { id: 'q7', text: 'Broad match with smart bidding works best when:', options: ['No data is available', 'Enough conversion data exists', 'You guess keywords', 'Competitors run TV ads'], correctOptionIndex: 1 },
      { id: 'q8', text: 'AI-based alerts help you identify:', options: ['CPL spikes', 'Food ordering', 'Colour mismatch', 'Designer workload'], correctOptionIndex: 0 },
      { id: 'q9', text: 'Automation tools include:', options: ['Pabbly', 'Zapier', 'Make', 'All'], correctOptionIndex: 3 },
      { id: 'q10', text: 'AI should:', options: ['Replace humans', 'Assist strategy', 'Remove reporting', 'Replace design'], correctOptionIndex: 1 },
    ],
  },
  'q_pm_m8': {
    id: 'q_pm_m8',
    title: 'Client Updates & Escalations Assessment',
    moduleId: 'pm_m8',
    totalQuestions: 10,
    timeLimit: '15:00',
    questions: [
      { id: 'q1', text: 'Performance specialist must update:', options: ['Designer', 'Account Manager', 'SEO', 'Only client'], correctOptionIndex: 1 },
      { id: 'q2', text: 'Red alerts include:', options: ['CTR increase', 'CPL spike or under-delivery', 'Good leads', 'High impressions'], correctOptionIndex: 1 },
      { id: 'q3', text: 'Updates must be:', options: ['Random', 'Proactive', 'Only monthly', 'Hidden'], correctOptionIndex: 1 },
      { id: 'q4', text: 'AM needs data to:', options: ['Create designs', 'Handle client calls', 'Write blogs', 'Manage SEO'], correctOptionIndex: 1 },
      { id: 'q5', text: 'Performance drops must be:', options: ['Hidden', 'Explained with data', 'Ignored', 'Celebrated'], correctOptionIndex: 1 },
      { id: 'q6', text: 'A recovery plan includes:', options: ['New audiences', 'New creatives', 'Bid changes', 'All of the above'], correctOptionIndex: 3 },
      { id: 'q7', text: 'Lead quality drops mean:', options: ['Pause all ads', 'Check CRM + adjust targeting', 'Change colours', 'Email support'], correctOptionIndex: 1 },
      { id: 'q8', text: 'If tracking breaks:', options: ['Run ads', 'Fix immediately', 'Ignore', 'Lower budgets'], correctOptionIndex: 1 },
      { id: 'q9', text: 'Updates help AM:', options: ['Lose trust', 'Align expectations with client', 'Delay work', 'Rebrand'], correctOptionIndex: 1 },
      { id: 'q10', text: 'Hiding issues leads to:', options: ['Bigger escalations', 'Better CPL', 'Happy clients', 'Higher CTR'], correctOptionIndex: 0 },
    ],
  },
  'q_pm_m9': {
    id: 'q_pm_m9',
    title: 'Process & SOP Adherence Assessment',
    moduleId: 'pm_m9',
    totalQuestions: 10,
    timeLimit: '15:00',
    questions: [
      { id: 'q1', text: 'SOPs exist to:', options: ['Confuse', 'Create consistency', 'Delay work', 'Reduce performance'], correctOptionIndex: 1 },
      { id: 'q2', text: 'Naming conventions must be:', options: ['Optional', 'Strictly followed', 'Hidden', 'Random'], correctOptionIndex: 1 },
      { id: 'q3', text: 'Documentation must include:', options: ['All changes', 'Only wins', 'Only budgets', 'Nothing'], correctOptionIndex: 0 },
      { id: 'q4', text: 'QC checklist is used:', options: ['After launch', 'Before launch', 'Never', 'Only for Meta'], correctOptionIndex: 1 },
      { id: 'q5', text: 'Tracking SOP ensures:', options: ['Wrong data', 'Correct conversions', 'Creative quality', 'More impressions'], correctOptionIndex: 1 },
      { id: 'q6', text: 'Audit reports help with:', options: ['Food orders', 'Identifying issues', 'Social media trends', 'Budget approval'], correctOptionIndex: 1 },
      { id: 'q7', text: 'SOP adherence prevents:', options: ['Scaling', 'Mistakes', 'CPC rise', 'Traffic drop'], correctOptionIndex: 1 },
      { id: 'q8', text: 'Escalation SOP requires:', options: ['Hiding issues', 'Root cause + action plan', 'Blaming designer', 'Pausing everything'], correctOptionIndex: 1 },
      { id: 'q9', text: 'Tracker updates must be:', options: ['Daily', 'Weekly', 'Monthly', 'Optional'], correctOptionIndex: 0 },
      { id: 'q10', text: 'Good SOP discipline leads to:', options: ['Chaos', 'Smooth operations', 'More mistakes', 'Delays'], correctOptionIndex: 1 },
    ],
  },
  'q_pm_m10': {
    id: 'q_pm_m10',
    title: 'Knowledge Transfer & Handover Assessment',
    moduleId: 'pm_m10',
    totalQuestions: 10,
    timeLimit: '12:00',
    questions: [
      { id: 'q1', text: 'KT is required:', options: ['Only sometimes', 'Before every leave', 'Only monthly', 'During vacations only'], correctOptionIndex: 1 },
      { id: 'q2', text: 'KT template must include:', options: ['Client details', 'Pending tasks', 'Red-alert items', 'All of the above'], correctOptionIndex: 3 },
      { id: 'q3', text: 'KT ensures:', options: ['Work stops', 'Smooth continuity', 'Higher CPL', 'More escalations'], correctOptionIndex: 1 },
      { id: 'q4', text: 'Access must be:', options: ['Ignored', 'Confirmed and shared', 'Removed', 'Skipped'], correctOptionIndex: 1 },
      { id: 'q5', text: 'Pending tasks must be:', options: ['Hidden', 'Clearly documented', 'Deleted', 'Delayed'], correctOptionIndex: 1 },
      { id: 'q6', text: 'For unplanned leave:', options: ['No KT needed', 'Minimal KT must be shared', 'Delete everything', 'Pause all ads'], correctOptionIndex: 1 },
      { id: 'q7', text: 'Walkthrough is for:', options: ['Confusing others', 'Ensuring replacement understands work', 'Showing designs', 'Updating AM'], correctOptionIndex: 1 },
      { id: 'q8', text: 'Screenshot or Loom videos help with:', options: ['Complex setups', 'Stories on Instagram', 'Competitor ads', 'Naming conventions'], correctOptionIndex: 0 },
      { id: 'q9', text: 'Updated trackers help prevent:', options: ['Clarity', 'Missed tasks', 'Smooth performance', 'Automatic scaling'], correctOptionIndex: 1 },
      { id: 'q10', text: 'Clean KT leads to:', options: ['Fewer errors', 'More escalations', 'Lower trust', 'Random work'], correctOptionIndex: 0 },
    ],
  },
  'q_pm_m11': {
    id: 'q_pm_m11',
    title: 'Conversion Tracking & LP Mgmt Assessment',
    moduleId: 'pm_m11',
    totalQuestions: 10,
    timeLimit: '18:00',
    questions: [
      { id: 'q1', text: 'Tracking must be verified:', options: ['After launch', 'Before launch', 'Only monthly', 'Only if CPL is high'], correctOptionIndex: 1 },
      { id: 'q2', text: 'Test leads must reflect in:', options: ['CRM + lead sheet', 'WhatsApp', 'Canva', 'Only GA4'], correctOptionIndex: 0 },
      { id: 'q3', text: 'UTMs track:', options: ['Design quality', 'Source/medium/campaign', 'Form colour', 'Website fonts'], correctOptionIndex: 1 },
      { id: 'q4', text: 'Landing page must be checked for:', options: ['Speed & CTA clarity', 'Only background colour', 'Hosting name', 'Comments'], correctOptionIndex: 0 },
      { id: 'q5', text: 'Rage clicks indicate:', options: ['Happy users', 'UX frustration', 'Fast loading', 'Good CRO'], correctOptionIndex: 1 },
      { id: 'q6', text: 'If LP form is not working:', options: ['Ignore it', 'Fix it immediately', 'Run ads anyway', 'Reduce budget'], correctOptionIndex: 1 },
      { id: 'q7', text: 'CRO improvements include:', options: ['Social proof', 'Sticky CTAs', 'Simpler forms', 'All of the above'], correctOptionIndex: 3 },
      { id: 'q8', text: 'Event mismatch causes:', options: ['Perfect data', 'Wrong tracking', 'High ROAS', 'Better CTR'], correctOptionIndex: 1 },
      { id: 'q9', text: 'Weekly LP sanity is needed because:', options: ['Code or plugin changes may break tracking', 'It’s optional', 'Designers like it', 'Hosting requires it'], correctOptionIndex: 0 },
      { id: 'q10', text: 'Bad landing pages lead to:', options: ['Lower CPL', 'Higher CPL and low conversions', 'Faster optimization', 'Better quality leads'], correctOptionIndex: 1 },
    ],
  },
  'q_pm_m12': {
    id: 'q_pm_m12',
    title: 'Audience, Keyword & Creative Strategy Assessment',
    moduleId: 'pm_m12',
    totalQuestions: 10,
    timeLimit: '18:00',
    questions: [
      { id: 'q1', text: 'Keyword research protects:', options: ['LP design', 'Budget from junk searches', 'Creative size', 'Fonts'], correctOptionIndex: 1 },
      { id: 'q2', text: 'High-intent keywords usually:', options: ['Convert better', 'Waste money', 'Have no clicks', 'Have no meaning'], correctOptionIndex: 0 },
      { id: 'q3', text: 'Audience clusters include:', options: ['Broad', 'Interests', 'Lookalikes', 'All of the above'], correctOptionIndex: 3 },
      { id: 'q4', text: 'Creative fatigue shows when:', options: ['CTR drops', 'CPL rises', 'Frequency increases', 'All of the above'], correctOptionIndex: 3 },
      { id: 'q5', text: 'Competitor creative research helps you:', options: ['Copy them', 'Understand angles that work', 'Delete ads', 'Pause campaigns'], correctOptionIndex: 1 },
      { id: 'q6', text: 'Creative ideas include:', options: ['UGC, testimonials, problem-solution', 'Only static images', 'Only text ads', 'Only carousels'], correctOptionIndex: 0 },
      { id: 'q7', text: 'Audience testing must be:', options: ['One time', 'Continuous', 'Rare', 'Avoided'], correctOptionIndex: 1 },
      { id: 'q8', text: 'AI helps generate:', options: ['CTA designs', 'Copy variations & hooks', 'Ad approvals', 'Form code'], correctOptionIndex: 1 },
      { id: 'q9', text: 'Frequency rising means:', options: ['Delivering new audience', 'Creative fatigue', 'New trends', 'LP is broken'], correctOptionIndex: 1 },
      { id: 'q10', text: 'Matching intent improves:', options: ['Fonts', 'CPL and lead quality', 'Colour palette', 'Video length'], correctOptionIndex: 1 },
    ],
  },
  'q_pm_m13': {
    id: 'q_pm_m13',
    title: 'Onboarding & New Client Setup Assessment',
    moduleId: 'pm_m13',
    totalQuestions: 10,
    timeLimit: '18:00',
    questions: [
      { id: 'q1', text: 'Onboarding prevents:', options: ['Future issues', 'Higher CPL', 'Fast fatigue', 'Client delays'], correctOptionIndex: 0 },
      { id: 'q2', text: 'Access must be:', options: ['Checked immediately', 'Ignored', 'Left for later', 'Sent to designer'], correctOptionIndex: 0 },
      { id: 'q3', text: 'Tracking setup includes:', options: ['GA4', 'GTM', 'Clarity', 'All'], correctOptionIndex: 3 },
      { id: 'q4', text: 'Test lead must reflect in:', options: ['CRM + lead sheet', 'WhatsApp only', 'Canva', 'Email only'], correctOptionIndex: 0 },
      { id: 'q5', text: 'CRO audit includes:', options: ['Speed', 'CTA clarity', 'Mobile check', 'All'], correctOptionIndex: 3 },
      { id: 'q6', text: 'First-month plan includes:', options: ['Audiences', 'Keywords', 'Budgets', 'All'], correctOptionIndex: 3 },
      { id: 'q7', text: 'Naming conventions must be:', options: ['Optional', 'Clean and SOP compliant', 'Random', 'Hidden'], correctOptionIndex: 1 },
      { id: 'q8', text: 'Kickoff ensures:', options: ['Miscommunication', 'Alignment', 'Delay', 'Confusion'], correctOptionIndex: 1 },
      { id: 'q9', text: 'Creative requirements must be shared:', options: ['After launch', 'Before campaign setup', 'Only when asked', 'Monthly'], correctOptionIndex: 1 },
      { id: 'q10', text: 'Missing tracking leads to:', options: ['Wrong data', 'Perfect reports', 'Creative wins', 'Strong CTR'], correctOptionIndex: 0 },
    ],
  },
  'q_pm_m14': {
    id: 'q_pm_m14',
    title: 'Tools, Diagnostics & Troubleshooting Assessment',
    moduleId: 'pm_m14',
    totalQuestions: 10,
    timeLimit: '18:00',
    questions: [
      { id: 'q1', text: 'Diagnostics help you:', options: ['Guess', 'Identify real issues', 'Delay work', 'Add more budgets'], correctOptionIndex: 1 },
      { id: 'q2', text: 'Low impressions require checking:', options: ['Audience size', 'Budget limits', 'Creative approvals', 'All'], correctOptionIndex: 3 },
      { id: 'q3', text: 'Debugging tracking uses:', options: ['Pixel Helper', 'GTM Preview', 'GA4 DebugView', 'All'], correctOptionIndex: 3 },
      { id: 'q4', text: 'Rage clicks mean:', options: ['Good UX', 'Frustration', 'No issue', 'Better CPL'], correctOptionIndex: 1 },
      { id: 'q5', text: 'Ad Rank issues show in:', options: ['Meta Stories', 'Google Diagnostics', 'Clarity heatmaps', 'WhatsApp'], correctOptionIndex: 1 },
      { id: 'q6', text: 'CRM mismatch must be:', options: ['Ignored', 'Fixed immediately', 'Hidden', 'Delayed'], correctOptionIndex: 1 },
      { id: 'q7', text: 'Performance drops may come from:', options: ['Competitors', 'Seasons', 'Fatigue', 'All'], correctOptionIndex: 3 },
      { id: 'q8', text: 'Event firing errors cause:', options: ['Perfect tracking', 'Wrong attribution', 'High CTR', 'More leads'], correctOptionIndex: 1 },
      { id: 'q9', text: 'Meta delivery issues include:', options: ['Learning fatigue', 'Audience overlap', 'Bid cap restrictions', 'All'], correctOptionIndex: 3 },
      { id: 'q10', text: 'Troubleshooting requires:', options: ['Random testing', 'Systematic root-cause analysis', 'Ignoring alerts', 'Lowering budgets only'], correctOptionIndex: 1 },
    ],
  },
  'q_pm_m15': {
    id: 'q_pm_m15',
    title: 'Red Alert Detection & Recovery Assessment',
    moduleId: 'pm_m15',
    totalQuestions: 10,
    timeLimit: '18:00',
    questions: [
      { id: 'q1', text: 'A red alert means:', options: ['Normal day', 'Sudden performance breakdown', 'Creative review', 'Weekly report'], correctOptionIndex: 1 },
      { id: 'q2', text: 'First step during red alert:', options: ['Panic', 'Diagnose root cause', 'Increase budget', 'Pause everything'], correctOptionIndex: 1 },
      { id: 'q3', text: 'Zero impressions may indicate:', options: ['Strong delivery', 'Rejection, bidding issues, or audience too narrow', 'Good CTR', 'Perfect CPL'], correctOptionIndex: 1 },
      { id: 'q4', text: 'High frequency + low CTR means:', options: ['Creative fatigue', 'Better performance', 'More reach', 'Less views'], correctOptionIndex: 0 },
      { id: 'q5', text: 'Tracking must be checked with:', options: ['Pixel Helper', 'GA4 DebugView', 'GTM preview', 'All'], correctOptionIndex: 3 },
      { id: 'q6', text: 'Lead quality drops require checking:', options: ['CRM data', 'Audience targeting', 'Ad message match', 'All'], correctOptionIndex: 3 },
      { id: 'q7', text: 'LP issues include:', options: ['Slow speed', 'Broken forms', 'Mobile layout errors', 'All'], correctOptionIndex: 3 },
      { id: 'q8', text: 'Fixing a red alert requires:', options: ['Recovery plan', 'New creatives', 'Audience expansion or bid changes', 'All'], correctOptionIndex: 3 },
      { id: 'q9', text: 'After fixing, you must:', options: ['Hide issue', 'Document cause + action', 'Delete logs', 'Pause ads'], correctOptionIndex: 1 },
      { id: 'q10', text: 'AM must receive:', options: ['No update', 'Clear explanation + recovery plan', 'Random screenshots', 'Irrelevant metrics'], correctOptionIndex: 1 },
    ],
  },
};